config/routes.rb
RubyPrueba::Application.routes.draw do 
  devise_for :usuarios
  get "sitio/inicio" => 'sitio#inicio', as: 'root'

  root :to => 'sitio#inicio'

  get "sitio/acerca" => 'sitio#about', as: 'acerca'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sitio_controller.rb
class SitioController < ApplicationController
  def inicio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sitio_helper.rb
module SitioHelper
end

app/views/layouts/_header.html.erb
<!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bootstrap theme</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Inicio", root_path %></li>
            <li><%= link_to "Acerca", acerca_path %></li>
            
          </ul>
          <ul class="nav navbar-nav pull-right">
            <% if usuario_signed_in? %>
              <li><%= link_to "Cerrar Sesion",  destroy_usuario_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Iniciar Sesion",  new_usuario_session_path %></li>    
            <% end %>        
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyPrueba</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header"%>
<div class="container">
	<% flash.each  do |name, msg|%>
		<%= content_tag(:div, msg, class: "alert alert-#(name)")%>
	<%end%>
<%= yield %>
<%= render "/sitio/footer"%>
</div>

app/views/sitio/_footer.html.erb
<div class="footer">
	<small>David Mera &#169; todos los derechos reservados.</small>
</div>

app/views/sitio/about.html.erb

<h1>About us<h1>
	<%= link_to "Enlace a Inicio", :controller => "sitio", :action => "inicio" %>
	<%= link_to "Enlace a oja.la", "https://oja.la" %>
<p>Page about us</p>

app/views/sitio/inicio.html.erb
<div class="jumbotron">
<h1>Bienvenidos</h1>

<%= link_to "Enlace a Inicio", "", :controller => :sitio, :action => :inicio, :method => :get, :class => "btn btn-primary btn-xs" %>
<%= link_to "Enlace a oja.la", "https://oja.la", :class => "btn btn-primary btn-xs" %>
<%= link_to "Registrate", new_usuario_registration_path, :class => "btn btn-primary btn-lg" %>
</div>